// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    book: require('./book'),
    user: require('./user'),
    permits: require('./permits'),
    permitClass: require('./permit_class')
  };
}).call(this);
